server:
  port: 8888
spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/virtual_world?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: exibxqS1-o
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  web:
    resources:
      static-locations:
        [ classpath:/resources/, classpath:/static/, classpath:/templates/]
      chain:
        strategy:
          content:
            paths: /**
            enabled: true